version: '3.8'

services:
  app:
    build: .
    container_name: vitazen-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
      # - kafka
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - kafka-network

  # kafka:
  #   image: wurstmeister/localhost:2.12-2.4.0
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - kafka-network

networks:
  kafka-network:
    driver: bridge
  app-network: 
    driver: bridge

volumes:
  mongodb_data:
